spring:
  application:
    name: job-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:job-service-db}?currentSchema=job_service
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    schemas: job_service
    default-schema: job_service
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: job_service
  cloud:
    config:
      enabled: false
  config:
    import: optional:classpath:application.dev.properties
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
server:
    port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true