spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: job-seeker-service
          uri: lb://JOB-SEEKER-SERVICE
          predicates:
            - Path=/api/job-seekers/**
        - id: job-seeker-service-educations
          uri: lb://JOB-SEEKER-SERVICE
          predicates:
            - Path=/api/educations/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true