spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: job-seeker-service
          uri: lb://JOB-SEEKER-SERVICE
          predicates:
            - Path=/api/job-seekers/**
        - id: recruiter-service
          uri: lb://RECRUITER-SERVICE
          predicates:
            - Path=/api/recruiters/**
        - id: job-service
          uri: lb://JOB-SERVICE
          predicates:
            - Path=/api/jobs/**
        - id: job-seeker-service-educations
          uri: lb://JOB-SEEKER-SERVICE
          predicates:
            - Path=/api/educations/**
        - id: job-seeker-service-skills
          uri: lb://JOB-SEEKER-SERVICE
          predicates:
            - Path=/api/skills/**
        - id: job-seeker-service-certifications
          uri: lb://JOB-SEEKER-SERVICE
          predicates:
            - Path=/api/certifications/**
        - id: job-seeker-service-experiences
          uri: lb://JOB-SEEKER-SERVICE
          predicates:
            - Path=/api/experiences/**
        - id: job-seeker-service-resumes
          uri: lb://JOB-SEEKER-SERVICE
          predicates:
            - Path=/api/resumes/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true