spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: user-service-db
  config:
    import: optional:classpath:application.dev.properties

server:
  port: 8081

springdoc:
  api-docs:
    path: /v3/api-docs

mongock:
  migration-scan-package: org.example.userservice.migration
  track-ignored: false
  enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
