spring:
  application:
    name: recruiter-service
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: recruiter-service-db
  cloud:
    config:
      enabled: false
  config:
    import: optional:classpath:application.dev.properties
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  bucket-name: ${AWS_BUCKET_NAME}

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true