spring:
  application:
    name: recruiter-service
  data:
    mongodb:
      uri: mongodb+srv://thevu29:thevu29@sjob.lgiue.mongodb.net/?retryWrites=true&w=majority&appName=SJob
      database: recruiter-service-db
  cloud:
    config:
      enabled: false

aws:
  access-key: AKIATJHQDR5H2YKXUDMY
  secret-key: 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
  region: ap-southeast-1
  bucket-name: sjob-storage

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true