
spring:
  application:
    name: recruiter-service
  data:
    mongodb:
      uri: mongodb+srv://thevu29:thevu29@sjob.lgiue.mongodb.net/?retryWrites=true&w=majority&appName=SJob
      database: recruiter-service-db
  cloud:
    config:
      enabled: false

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true