spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/sjob"
          jwk-set-uri: "http://localhost:9090/realms/sjob/protocol/openid-connect/certs"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # Swagger docs
        - id: application-service-api-docs
          uri: lb://APPLICATION-SERVICE
          predicates:
            - Path=/application-service/v3/api-docs/**
          filters:
            - RewritePath=/application-service(?<segment>/?.*), /${segment}

        - id: user-service-api-docs
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/v3/api-docs/**
          filters:
            - RewritePath=/user-service(?<segment>/?.*), /${segment}

        - id: job-seeker-service-api-docs
          uri: lb://JOB-SEEKER-SERVICE
          predicates:
            - Path=/job-seeker-service/v3/api-docs/**
          filters:
            - RewritePath=/job-seeker-service(?<segment>/?.*), /${segment}

        - id: auth-service-api-docs
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/v3/api-docs/**
          filters:
            - RewritePath=/auth-service(?<segment>/?.*), /${segment}

        # API routes
        - id: application-service
          uri: lb://APPLICATION-SERVICE
          predicates:
            - Path=/api/applications/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

        - id: job-seeker-service
          uri: lb://JOB-SEEKER-SERVICE
          predicates:
            - Path=/api/job-seekers/**
        - id: job-seeker-service-educations
          uri: lb://JOB-SEEKER-SERVICE
          predicates:
            - Path=/api/educations/**
        - id: job-seeker-service-skills
          uri: lb://JOB-SEEKER-SERVICE
          predicates:
            - Path=/api/skills/**
        - id: job-seeker-service-certifications
          uri: lb://JOB-SEEKER-SERVICE
          predicates:
            - Path=/api/certifications/**
        - id: job-seeker-service-experiences
          uri: lb://JOB-SEEKER-SERVICE
          predicates:
            - Path=/api/experiences/**
        - id: job-seeker-service-resumes
          uri: lb://JOB-SEEKER-SERVICE
          predicates:
            - Path=/api/resumes/**

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: recruiter-service
          uri: lb://RECRUITER-SERVICE
          predicates:
            - Path=/api/recruiters/**

        - id: job-service
          uri: lb://JOB-SERVICE
          predicates:
            - Path=/api/jobs/**

springdoc:
  swagger-ui:
    urls:
      - name: User Service
        url: /user-service/v3/api-docs
      - name: Job Seeker Service
        url: /job-seeker-service/v3/api-docs
      - name: Auth Service
        url: /auth-service/v3/api-docs
      - name: Application Service
        url: /application-service/v3/api-docs
    disable-swagger-default-url: true
    path: /swagger-ui.html
    api-docs:
      enabled: true

server:
  port: 8080