spring:
  kafka:
    bootstrap-servers: kafka:19092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: application-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://keycloak:8080/realms/sjob"
          jwk-set-uri: "http://keycloak:8080/realms/sjob/protocol/openid-connect/certs"
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: application-service-db

mongock:
  migration-scan-package: org.example.applicationservice.database.migration
  track-ignored: false
  enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs

server:
  port: 8088

gateway:
  url: ${GATEWAY_URL}

eureka:
  instance:
    hostname: application-service
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

service:
  job-seeker:
    url: http://job-seeker-service:8082
  recruiter:
    url: http://recruiter-service:8083
  job:
    url: http://job-service:8084

keycloak:
  client:
    client-id: application-service
    client-secret: ${KEYCLOAK_APPLICATION_SERVICE_CLIENT_SECRET}
    token-uri: http://keycloak:8080/realms/sjob/protocol/openid-connect/token

management:
  endpoints:
    web:
      exposure:
        include: health,info
