eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

name:
  value: sjob

spring:
  cloud:
    config:
      override-system-properties: false