eureka:
  instance:
    hostname: discovery-server
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

spring:
  cloud:
    config:
      override-system-properties: false
  kafka:
    bootstrap-servers: kafka:19092

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
