spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/sjob"
          jwk-set-uri: "http://localhost:9090/realms/sjob/protocol/openid-connect/certs"
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

springdoc:
  api-docs:
    path: /v3/api-docs

server:
  port: 8085

gateway:
  url: ${gateway.url}

service:
  user:
    url: http://localhost:8081
  job-seeker:
    url: http://localhost:8082
  recruiter:
    url: http://localhost:8083

keycloak:
  server-url: http://localhost:9090
  realm: sjob
  client-id: admin-cli
  username: admin
  password: admin
  client:
    client-id: auth-service
    client-secret: ${keycloak.auth-service.client.secret}