spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/sjob"
          jwk-set-uri: "http://localhost:9090/realms/sjob/protocol/openid-connect/certs"
  datasource:
    url: jdbc:postgresql://${db.host:localhost}:${db.port:5432}/${db.database:job-service-db}?currentSchema=job_service
    username: ${db.user:postgres}
    password: ${db.password:123}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    schemas: job_service
    default-schema: job_service
    baseline-version: 0
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: job_service
  #  cloud:
  #    config:
  #      enabled: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

springdoc:
  api-docs:
    path: /v3/api-docs

server:
  port: 8084

gateway:
  url: ${gateway.url}

service:
  recruiter:
    url: http://localhost:8083

keycloak:
  client:
    client-id: job-service
    client-secret: ${keycloak.job-service.client.secret}
    token-uri: http://localhost:9090/realms/sjob/protocol/openid-connect/token