spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://keycloak:8080/realms/sjob"
          jwk-set-uri: "http://keycloak:8080/realms/sjob/protocol/openid-connect/certs"
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    schemas: job_service
    default-schema: job_service
    baseline-version: 0
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: job_service
  kafka:
    bootstrap-servers: kafka:19092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

mongock:
  migration-scan-package: com.example.jobservice.database.migration
  track-ignored: false
  enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs

server:
  port: 8084

gateway:
  url: ${GATEWAY_URL}

service:
  recruiter:
    url: http://recruiter-service:8083
  user:
    url: http://user-service:8081

keycloak:
  client:
    client-id: job-service
    client-secret: ${KEYCLOAK_JOB_SERVICE_CLIENT_SECRET}
    token-uri: http://keycloak:8080/realms/sjob/protocol/openid-connect/token

eureka:
  instance:
    hostname: job-service
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
