spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/sjob"
          jwk-set-uri: "http://localhost:9090/realms/sjob/protocol/openid-connect/certs"
  data:
    mongodb:
      uri: ${mongo.uri}
      database: recruiter-service-db
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

aws:
  access-key: ${aws.access-key}
  secret-key: ${aws.secret-key}
  region: ${aws.region}
  bucket-name: ${aws.bucket-name}

springdoc:
  api-docs:
    path: /v3/api-docs

server:
  port: 8083

gateway:
  url: ${gateway.url}

service:
  user:
    url: http://localhost:8081
  notification:
    url: http://localhost:8086
  job:
    url: http://localhost:8084
  jobSeeker:
    url: http://localhost:8082

keycloak:
  client:
    client-id: recruiter-service
    client-secret: ${keycloak.recruiter-service.client.secret}
    token-uri: http://localhost:9090/realms/sjob/protocol/openid-connect/token