spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/sjob"
          jwk-set-uri: "http://localhost:9090/realms/sjob/protocol/openid-connect/certs"
  data:
    mongodb:
      uri: ${mongo.uri}
      database: recruiter-service-db
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

aws:
  access-user-key: ${aws.access.user.key}
  secret-user-key: ${aws.secret.user.key}
  region: ${aws.region}
  bucket-name: ${aws.bucket.name}

springdoc:
  api-docs:
    path: /v3/api-docs

server:
  port: 8083

gateway:
  url: ${gateway.url}

service:
  user:
    url: http://localhost:8081

keycloak:
  client:
    client-id: recruiter-service
    client-secret: ${keycloak.recruiter-service.client.secret}
    token-uri: http://localhost:9090/realms/sjob/protocol/openid-connect/token