spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/sjob"
          jwk-set-uri: "http://localhost:9090/realms/sjob/protocol/openid-connect/certs"
  data:
    mongodb:
      uri: ${mongo.uri}
      database: report-service-db

aws:
  access-key: ${aws.access-key}
  secret-key: ${aws.secret-key}
  region: ${aws.region}
  bucket-name: ${aws.bucket-name}

springdoc:
  api-docs:
    path: /v3/api-docs

server:
  port: 8088

gateway:
  url: ${gateway.url}

service:
  recruiter:
    url: http://localhost:8083
  jobSeeker:
    url: http://localhost:8082

keycloak:
  client:
    client-id: report-service
    client-secret: ${keycloak.report-service.client.secret}
    token-uri: http://localhost:9090/realms/sjob/protocol/openid-connect/token