spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/sjob"
          jwk-set-uri: "http://localhost:9090/realms/sjob/protocol/openid-connect/certs"
  data:
    mongodb:
      uri: ${mongo.uri}
      database: user-service-db

mongock:
  migration-scan-package: org.example.userservice.database.migration
  track-ignored: false
  enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs

server:
  port: 8081

gateway:
  url: ${gateway.url}

service:
  notification:
    url: http://localhost:8086

keycloak:
  server-url: http://localhost:9090
  realm: sjob
  client-id: admin-cli
  username: admin
  password: admin
  client:
    client-id: user-service
    client-secret: ${keycloak.user-service.client.secret}
    token-uri: http://localhost:9090/realms/sjob/protocol/openid-connect/token