spring:
  profiles:
    active: native
  application:
    name: config-server
  config:
    import: optional:classpath:application.env.yml
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
        overrides:
          mongo:
            uri: ${mongo.uri}
          db:
            host: ${db.host}
            port: ${db.port}
            database: ${db.database}
            user: ${db.user}
            password: ${db.password}
          aws:
            region: ${aws.region}
            access-key: ${aws.access-key}
            secret-key: ${aws.secret-key}
            bucket-name: ${aws.bucket-name}
            access-user-key: ${aws.access-user-key}
            secret-user-key: ${aws.secret-user-key}
          gateway:
            url: ${gateway.url}
          keycloak:
            auth-service:
              client:
                secret: ${keycloak.auth-service.client.secret}
            job-seeker-service:
              client:
                secret: ${keycloak.job-seeker-service.client.secret}
            recruiter-service:
              client:
                secret: ${keycloak.recruiter-service.client.secret}
            job-service:
              client:
                secret: ${keycloak.job-service.client.secret}
            notification-service:
              client:
                secret: ${keycloak.notification-service.client.secret}
          mail:
            username: ${mail.username}
            password: ${mail.password}

server:
  port: 8888