mongo:
  uri:

db:
  host:
  port:
  database:
  user:
  password:

aws:
  region:
  access-key:
  secret-key:
  bucket-name:
  access-user-key:
  secret-user-key:

gateway:
  url:

keycloak:
  auth-service:
    client:
      secret:
  job-seeker-service:
    client:
      secret:
  job-service:
    client:
      secret:
  recruiter-service:
    client:
      secret:

mail:
  username:
  password: