spring:
  profiles:
    active: native
  application:
    name: config-server
  config:
    import: optional:classpath:application.env.properties
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
        overrides:
          mongo.uri: ${mongo.uri}
          db.host: ${db.host}
          db.port: ${db.port}
          db.database: ${db.database}
          db.user: ${db.user}
          db.password: ${db.password}
          aws.region: ${aws.region}
          aws.access.key: ${aws.access.key}
          aws.secret.key: ${aws.secret.key}
          aws.bucket.name: ${aws.bucket.name}

server :
  port: 8888